### PR TITLE
User_interface with prompts to get the players information 

### PR DESCRIPTION
**Pull request by cgcarlosg**
Add lines in order to collect the basic information to play the tic-tac-toe game

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @cgcarlosg and @Huemac-Alfredo  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Please run this command `chmod 755 bin/main.rb` to make your `main.rb` file executable
- [ ] In this step you are supposed to only mock the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (gets.chomp). No game logic (for example checking who is a winner) is required in this milestone - instead, you can just display "The winner is X" no matter who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game tells which player turn it is (without computing who the winner is)
- [ ] Game asks the player to select from available moves
- [ ] Game informs player if the selected move is invalid (without computing what an invalid move is)
- [ ] Game displays board after the player move (without computing which spots on the board are taken)
- [ ] Game informs player if the selected move is a winning move (without computing the winning move)
- [ ] Game informs player if the selected move is a draw move (without computing draw)
- [ ] Game repeats all actions for the next player's move

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Comment by cgcarlosg** [comment]
The file has the input   #!/usr/bin/env ruby     at the beginning.  However when it is run chmod 755 bin/main.rb nothing changes and the linters is still reporting "file does not have  execute permission". Is it possible an additional help for this?

**Comment by descholar-ceo** [comment]
> The file has the input #!/usr/bin/env ruby at the beginning. However when it is run chmod 755 bin/main.rb nothing changes and the linters is still reporting "file does not have execute permission". Is it possible an additional help for this?

@cgcarlosg have you tried to read this ? https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @cgcarlosg  & @Huemac-Alfredo**


Great job with the project so far, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] you have to make the main.rb file executable, if you can't seem to solve the problem then you can schedule a meeting with a full time tse from [here](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by alfredoC10** [comment]
Thank you guys for your heartening and timely words. Your advices are being followed. No doubt they´ll mark a positive difference in what we do!

**Review by SpaYco — APPROVED** [review]
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by cgcarlosg** [comment]
user_interface merged with development branch

**Pull request merged**
