### PR TITLE
Setting up repository

### PR DESCRIPTION
**Pull request by alfredoC10**
This repository was set up with linters and base directories

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @Huemac-Alfredo and @cgcarlosg  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]
- [ ] `bin/main.rb` file should be executable and should be displaying `Hello world!` as a message when I run `bin/main.rb`, [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from the [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/), :point_right:  [Read here](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/) to know how to make a ruby file executable

# [Optional changes]
- [ ] Your commit message should be in imperative mode or present tense, _i.e.:_ you should have written `Add my empty directory` instead of writting `Adding my empty directory`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done great on this milestone sofar!

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [ ] `main.rb` should be executable. 
Add `#!/usr/bin/env ruby` to the top line
Add `puts "Hello world"` in the following line
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. :+1:
- [OPTIONAL]: remove `to the top line` from the first line in your `main.rb` file. Just leave it as `#!/usr/bin/env ruby`. 

- [OPTIONAL]: Give your branches more meaningful names, so instead of just `feature`, you can call it something like `project-setup-feature` or anything along those lines.

You can merge this branch into the developemnt branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Comment by cgcarlosg** [comment]
First Milestone Approved

**Review by cgcarlosg — COMMENTED** [review]
ok

**Review by cgcarlosg — COMMENTED** [review]
ok

**Review by cgcarlosg — COMMENTED** [review]
ok

**Review by cgcarlosg — COMMENTED** [review]
ok

**Pull request closed without merging**
